-
  srvtype: Google+
  link: https://plus.google.com/u/2/106669966380206498641
  description:
    - >
      Learn about newest news and happenings in and around AOSC.
-
  srvtype: Public Clipboard
  link: https://pastebin.aosc.io
  description:
    - >
      Our public clipboard service (or pastebin) that you can use for all your
      clippy needs.
-
  srvtype: Hermes WebMail
  link: https://hermes.aosc.io
  description:
    - >
      Our WebMail service for AOSC developers and contributors.
-
  srvtype: Community Repository
  link: https://repo.aosc.io
  description:
    - >
      Our community repository server, where AOSC OS installation medias,
      tarballs, packages, project documentation, etc. are stored.
-
  srvtype: IRC Channel
  link: https://webchat.freenode.net/?channels=%23aosc
  description:
    - >
      Get in touch with the community.
-
  srvtype: Mirror Status
  link: /mirror-status
  description:
    - >
      Take a look at current mirror synchronization and availability information.
